version: '2'
services:
  mc-server:
    network_mode: host
    restart: always
    build: ./mc-server
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - serverfiles:/usr/src/serverfiles
      - servercache:/servercache
    ports:
      - "25565:25565/udp"
      - "25565:25565/tcp"
      - "25575:25575/udp"
      - "25575:25575/tcp"
  scp-server:
    network_mode: host
    restart: always
    build: ./scp-server
    privileged: false
    labels:
      io.balena.features.dbus: 1
    volumes:
      - serverfiles:/serverfiles
      - servercache:/servercache
    ports:
      - "22:22/udp"
      - "22:22/tcp"
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  balena-rcon:
    network_mode: host
    restart: always
    build: ./balena-rcon
    privileged: true
    ports:
      - "25575:25575/udp"
      - "25575:25575/tcp"
volumes:
  serverfiles:
  servercache:
